import type { Metadata } from "next";
import { Manrope, Work_Sans } from "next/font/google";
import "./theme.css";

const manRope = Manrope({
  variable: "--md-ref-typeface-brand",
  subsets: ["latin"],
  weight: ["400"]
})

const workSans = Work_Sans({
  variable: "--md-ref-typeface-plain",
  subsets: ["latin"]
})

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manRope.variable} ${workSans.variable} antialiased ref light`}
      >
        {children}
      </body>
    </html>
  );
}
